[tool.poetry]
name = "ppi"
version = "0.1.0"
description = ""
authors = ["justin <justinjagoss@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pandas = "^2.2.3"
requests = "^2.32.3"
pydantic = "^2.10.6"
pandera = "^0.22.1"
matplotlib = "^3.10.0"
pytest-mock = "^3.14.0"
fuzzywuzzy = "^0.18.0"
setuptools = "^75.8.0"
numpy = "^1.23"
sqlalchemy = "^2.0.0"


[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
    "isort>=5.0",
    "mypy>=1.0",
    "ruff>=0.1.0",
]
docs = [
    "sphinx>=7.0",
    "sphinx-rtd-theme>=1.0",
]

[project.urls]
Homepage = "https://github.com/jjagoss/ppi"
Documentation = "https://ppi.readthedocs.io"


[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"